services:
  - type: web
    name: leadpages-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 300
    repo: https://github.com/Kh3rwa1/viralproject
    branch: main
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
